export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const FETCH_USERS = 'FETCH_USERS';
export const SET_TOKEN = 'SET_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';

export const ACCOUNT_CREATION_STARTED = 'ACCOUNT_CREATION_STARTED';
export const ACCOUNT_CREATION_COMPLETED = 'ACCOUNT_CREATION_COMPLETED';
export const ACCOUNT_CREATION_FAILED = 'ACCOUNT_CREATION_FAILED';

export const ORGANIZATION_CREATION_STARTED = 'ORGANIZATION_CREATION_STARTED';
export const ORGANIZATION_CREATION_COMPLETED = 'ORGANIZATION_CREATION_COMPLETED';
export const ORGANIZATION_CREATION_FAILED = 'ORGANIZATION_CREATION_FAILED';

export const ERROR = 'ERROR';

// export const ADD_USER = 'ADD_USER'
// export const ADD_USER = 'ADD_USER'
// export const ADD_USER = 'ADD_USER'
// export const ADD_USER = 'ADD_USER'
// export const ADD_USER = 'ADD_USER'
