export const REGISTRATION_STARTED = 'REGISTRATION_STARTED';
export const REGISTRATION_COMPLETED = 'REGISTRATION_COMPLETED';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_COMPLETED = 'LOGIN_COMPLETED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT = 'LOGOUT';

export const SET_TOKEN = 'SET_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';

export const ACCOUNT_CREATION_STARTED = 'ACCOUNT_CREATION_STARTED';
export const ACCOUNT_CREATION_COMPLETED = 'ACCOUNT_CREATION_COMPLETED';
export const ACCOUNT_CREATION_FAILED = 'ACCOUNT_CREATION_FAILED';

export const ORGANIZATION_CREATION_STARTED = 'ORGANIZATION_CREATION_STARTED';
export const ORGANIZATION_CREATION_COMPLETED = 'ORGANIZATION_CREATION_COMPLETED';
export const ORGANIZATION_CREATION_FAILED = 'ORGANIZATION_CREATION_FAILED';

export const ERROR = 'ERROR';

// export const ADD_USER = 'ADD_USER'
// export const ADD_USER = 'ADD_USER'
// export const ADD_USER = 'ADD_USER'
// export const ADD_USER = 'ADD_USER'
// export const ADD_USER = 'ADD_USER'
