export const REGISTRATION_STARTED = 'REGISTRATION_STARTED';
export const REGISTRATION_COMPLETED = 'REGISTRATION_COMPLETED';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const TOGGLE_RIGHT_SIDEBAR = 'TOGGLE_RIGHT_SIDEBAR';
export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_COMPLETED = 'LOGIN_COMPLETED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REMOVE_USER = 'REMOVE_USER';
export const USER_DATA_FETCHING = 'USER_DATA_FETCHING';
export const USER_DATA_FETCHING_FAILED = 'USER_DATA_FETCHING_FAILED';
export const SET_USERS_STARTED = 'SET_USERS_STARTED';
export const SET_USERS = 'SET_USERS';

export const LOGOUT = 'LOGOUT';

export const SET_TOKEN = 'SET_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';

export const ACCOUNT_CREATION_STARTED = 'ACCOUNT_CREATION_STARTED';
export const ACCOUNT_CREATION_COMPLETED = 'ACCOUNT_CREATION_COMPLETED';
export const ACCOUNT_CREATION_FAILED = 'ACCOUNT_CREATION_FAILED';
export const SET_ACCOUNT_DETAILS = 'SET_ACCOUNT_DETAILS';
export const REMOVE_ACCOUNT_DETAILS = 'REMOVE_ACCOUNT_DETAILS';
export const SET_ACCOUNTS = 'SET_ACCOUNTS';

export const ORGANIZATION_CREATION_STARTED = 'ORGANIZATION_CREATION_STARTED';
export const ORGANIZATION_CREATION_COMPLETED =
	'ORGANIZATION_CREATION_COMPLETED';
export const ORGANIZATION_CREATION_FAILED = 'ORGANIZATION_CREATION_FAILED';
export const SET_ORGANIZATION_DETAILS = 'SET_ORGANIZATION_DETAILS';
export const REMOVE_ORGANIZATION_DETAILS = 'REMOVE_ORGANIZATION_DETAILS';
export const SET_CURRENT_ORG = 'SET_CURRENT_ORG';
export const REMOVE_CURRENT_ORG = 'REMOVE_CURRENT_ORG';
export const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS';

export const FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS';

export const ERROR = 'ERROR';

// export const ADD_USER = 'ADD_USER'
// export const ADD_USER = 'ADD_USER'
// export const ADD_USER = 'ADD_USER'
// export const ADD_USER = 'ADD_USER'
// export const ADD_USER = 'ADD_USER'
